sudo: required
dist: trusty

language: c

os:
    - linux

compiler:
    - gcc

addons:
    apt:
        packages:
            - autopoint
            - python-lxml
            - libgl1-mesa-dev

cache:
    directories:
        - protobuf

env:
    global:
        # GH_TOKEN scope=public_repo, for pushing to gh-pages demo site,
        # limited to builds of the rib/gputop repo
        - secure: "CXTLgHD8PYC3OQO88QHFaCu6tfF4Pp/fHvn9cguOptBUrkOad5IKq43r4wNv+VFKl9f99K4tvBThHOLAryi+2OFDwkKIiIHfhyaEewLQKFOxGlXLQf6JlKslzVU8/r5BeKt1KH1fuNmaqGqyv39snVmBE0HGmHntpY8U0CtISwL8riS8fQWT/Ae3vUVDnkCaHen6QfCvOQtwZey7GwFp2+Dn7lVC4xviOTR2zEydMzRnvhzwO4NkeCtigqgY5jEW6Irmk72Ng/27UTYY/ps+/dvtLeL2xGWziPRWf92z6qMGJAuX6CfAkwPHF4G/MNnOSQ2R3YZPDPzSLitpz/ThXnpfUlJMpa7fV/RZMp9+WjbSvyfi4mUG+fyvWPS3oXkF05U5rmZn5LHrTvjFUXt7lj3n/Ugkk2+1dTFxwHE1HzV85C1kNgOIgwhJLvfddyhUncwBHKMUs6q5w9sha+5zMF0YTttG8EJFwHKqjCdwycJ5g1/i0mmj6qzTFosUmH0N+3bIPAO/ca6DjUXzoH1f0BeL22M3Uy3CEeWgfn7X87fRGK8pgHE6d3VYb6VdO8ys17Cz3SkRn4S71VwXqZg6nl462C/nUR23Rpi/ijYWhPYAqXVGPUsCOAzUl1PTBMDsHqWk2hUto2WEXCnVhpBoq5FkJ0RhV03tPyAZCtoCNcw="
    matrix:
        - CONFIG_OPTS="--enable-debug --enable-gl --disable-webui"
        - CONFIG_OPTS="--disable-debug --enable-gl --disable-webui"
        - CONFIG_OPTS="--enable-debug --disable-gl --disable-webui"
        - CONFIG_OPTS="--disable-debug --disable-gl --disable-webui"
        - CONFIG_OPTS="--enable-debug --disable-gl --enable-webui"
        - CONFIG_OPTS="--disable-debug --disable-gl --enable-webui"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y emscripten
    - emcc -v
    - (if test -d protobuf/lib; then echo OK; else
            git clone --single-branch --branch master --depth 1 https://github.com/google/protobuf protobuf-src &&
            cd protobuf-src &&
            ./autogen.sh &&
            ./configure --prefix=$TRAVIS_BUILD_DIR/protobuf &&
            make &&
            make install;
       fi)
    - export PKG_CONFIG_PATH="$TRAVIS_BUILD_DIR/protobuf/lib/pkgconfig"
    # Fetch glext.h header including INTEL_performance_query enums
    - $(mkdir GL && cd GL && wget https://raw.githubusercontent.com/rib/mesa/wip/rib/oa-next/include/GL/glext.h)
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

before_script:
    - NOCONFIGURE=1 ./autogen.sh

script:
    - ./configure $CONFIG_OPTS --prefix=$TRAVIS_BUILD_DIR/install && make V=1 && make V=1 install
    - export GPUTOP_TRAVIS_MODE=1
    - cd $TRAVIS_BUILD_DIR/install/bin
    - ./gputop --fake ./gputop-system
    - if [ "${CONFIG_OPTS/'enable-webui'}" != "$CONFIG_OPTS" ]; then ./gputop --fake --remote ./gputop-system 2> travis_log& sleep 3; firefox http://localhost:7890& sleep 10; grep OpenQuery travis_log; cat travis_log; fi
    - cd -

deploy:
    provider: script
    script: ./scripts/deploy-demo-site.sh
    skip_cleanup: true
    on:
        condition: $CONFIG_OPTS = "--disable-debug --disable-gl --enable-webui"
        branch: master
